name: reels
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  arcade:
    git:
      url: https://github.com/ishafiul/arcade.git
      ref: fix/process_signal_watchers_windows
      path: packages/arcade/
  envied: ^0.5.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  orm: ^3.4.3
  postgres: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  json_serializable: ^6.7.0
  injectable_generator: ^2.4.1
  lint:
  test: ^1.25.0