targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          scalars:
            GeoJsonPointCoordinatesScalar:
              type: List<double>
            GeoJsonLineStringCoordinatesScalar:
              type: List<List<double>>
            GeoJsonPolygonCoordinatesScalar:
              type: List<List<List<double>>>
            IsoDate:
              type: String